### ISSUE TITLE
support for images, serialized files, 

### ISSUE THREAD

**Issue by vankesteren** [J535D165/scitree#1]
Great project! 

- A lot of scientific projects also have images as output (or input). I would put those in a grey colour.
- Another important file type is binary or serialized data. For R, that would be `.rds`, for python that's commonly `.pkl`. `.bin` could be another. This could also be under the "data" label.
- Maybe there's something to be said for config files (`.Rproj`, `.toml`, etc.)

In general, would it not be a good idea to have the filetype extension filters depend on something external? I tried scitree out on one of my projects, and for example it did not recognise my `.stan` files as code.

**Comment by JTeijema** [comment]
I want to contribute icon mode, which required me to recognize figures. I've started this in #4

**Comment by JTeijema** [comment]
As the terminal usually has no grey color option, I chose yellow (the other contender, white)

**Comment by JTeijema** [comment]
For serialized files, I've added 
```python
SERIALDATA_SUFFIXES = [".rds",".pkl",".bin",".h5",".hdf5",".mat",".sav",".dta",".sas7bdat",".feather",".parquet"]

**Comment by JTeijema** [comment]
I had an issue passing the style function in the scitree function to the formatter. Credits to ChatGPT for the solution 😉 .


Here is how you can modify the scitree function to pass the icons argument to the natsort_scitree_style function:

```python
def scitree(
    p=".",
    sort=True,
    sort_key=scisort_keygen(),
    formatter=lambda: natsort_scitree_style(icons=True),  # modified
    gitignore=True,
    first="files",
    exclude_folders=[".git"],
    icons=True,
    **kwargs
):
    sd.seedir(
        str(p),
        sort=sort,
        sort_key=sort_key,
        formatter=formatter,
        first=first,
        mask=gi_mask,
        exclude_folders=exclude_folders,
        **kwargs
    )
```

The lambda function will create a new function that calls natsort_scitree_style with the icons argument set to True, and this new function will be passed to the seedir function as the formatter argument.

Alternatively, you can define a separate function that calls natsort_scitree_style with the icons argument, and pass this function to the seedir function as the formatter argument.
    sort=
