### ISSUE TITLE
directory count includes git tree?

### ISSUE THREAD

**Issue by vankesteren** [J535D165/scitree#2]
I have a small project with only a few directories, yet scitree prints the following:

![image](https://user-images.githubusercontent.com/11596858/198580424-9251268a-c526-442e-9f85-5e4669345d3a.png)

perhaps that's because it is including the .git directory and its subdirectories in the count?

**Comment by J535D165** [comment]
Thanks for reporting. This is related to the `.git` folder indeed. Fix in #3.
